### ISSUE TITLE
Страница /version

### ISSUE THREAD

**Issue by HadronCollider** [OSLL/MD-Code_generator#13]
- Скрипт, формирующий файл с необходимой информацией
  - Аналогично: https://github.com/moevm/mse_auto_checking_slides_vaganov/blob/master/scripts/version.sh
- Роут /version отображающий страницу с информаицией из файла ^
  - Аналогично http://slides-checker.moevm.info/version

P.S. Branch name можно убрать (при текущем подходе к деплою она недоступна на сервере)

**Comment by neckbosov** [comment]
Несколько вопросов:

1. Нужен именно файл или только страничка?
2. Мы же не копируем информацию про git в контейнер, эта информация вообще пустой будет по факту.

**Comment by HadronCollider** [comment]
1. Нужен скрипт для генерации и страница, отображающая содержимое файла
2. Файл генерируется до создания контейнера
