### ISSUE TITLE
Логгирование системы

### ISSUE THREAD

**Issue by HadronCollider** [OSLL/MD-Code_generator#14]
- Кастомный обработчик для логгера (для записи логов в файл, а в будущем в БД)

В качестве логов системы сейчас может выступать печать содержимого #17 при запуске

**Comment by mandelshtamd** [comment]
Мы хотим, чтобы все логи писались в один файл (то есть был файл, в котором на верхнем уровне будет массив для джейсонов) или чтобы для каждой отдельной записи появлялся новый файл, в котором был бы json для конкретной записи?
