### ISSUE TITLE
Добавить роут для получения бинарного файла

### ISSUE THREAD

**Issue by HadronCollider** [OSLL/MD-Code_generator#24]
Роут для отправки картинки в бинарном виде

В качестве проверки - изображение должно быть доступно на html-странице в теге img, атрибут `src` которого содержит полный URL (html-страницу добавлять не нужно - смотреть её локально)

**Comment by neckbosov** [comment]
Можно пояснить что значит второй абзац? У нас же уже отправляется страница с URL к существующей картинке. Или это имеется в виду что надо продумать как локально хранить картинки?

**Comment by neckbosov** [comment]
Не очень понятно как без доменного имени выставлять URL в src

**Comment by HadronCollider** [comment]
> Можно пояснить что значит второй абзац? У нас же уже отправляется страница с URL к существующей картинке. Или это имеется в виду что надо продумать как локально хранить картинки?

- `У нас же уже отправляется страница с URL к существующей картинке` - это роут `/get_image`, работа которого нас не устраивает (возвращает *страницу*)
- В рамках задачи нужно добавить новый роут (условно `/raw_image`), который возвращает не html-страницу, а файл (который затем можно использовать на клиента)

> Не очень понятно как без доменного имени выставлять URL в src. Если это только для проверки, надо ли удалять тогда уже имеющуюся страницу?

- Имеющуюся страницу удалять не нужно, как и менять существующий роут (потом вы их просто уберем/заменим)
- Для локальной проверки -> домен `localhost` или я неверно понял вопрос?
