### ISSUE TITLE
Анализ существующих способов генерации изображений

### ISSUE THREAD

**Issue by HadronCollider** [OSLL/MD-Code_generator#3]
Возможно, появились новые способы генерации изображений (используемые сейчас в проекте за 1,5 года могли устареть), либо 

Результат: вики-страница с описанием текущего подхода (в проекте) к генерации изображения, сравнительный анализ с новыми решениями/современными версиями текущего подхода (если он обновлялся)

**Comment by mandelshtamd** [comment]
Изучил какие есть варианты поддержки подсветки: 

- Есть некоторые готовые апишки, которые как раз решают нашу задачу (основные 2 сервиса, с которыми можно взаимодействовать через апи: [code2img](https://code2img.com/), [carbon](https://carbon.now.sh/). Они поддерживают многие языки, в том числе те, которые нам в первую очередь интересны (C, Python, PHP). Также есть широкие возможности для того, чтобы дизайнить внешний вид помимо подсветки, например, background, font size, и многое другое.
У такого подхода есть проблемы, о которых надо подумать: через эти сервисы нельзя добавлять искажения и мы будем зависимы от работы сервисов. Можно добавлять искажения самостоятельно, но тогда либо это будет искажение не текста, а картинки, либо придется сильно париться насчет text recognition и кажется на это сейчас времени нет.

-Каких-то либ под жвм, которые бы оффлайн помогли нам с подсветкой я не нашел(кажется, их нет). С искажением справляется и текущая либа. Есть прямолинейное решение - захардкодить сишные ключевые слова и самим их красить, но это не масштабируемое решение и выйдет не ахти какая подсветка, если поддерживать только ключевые слова, так что думаю это плохой вариант.
